[project]
name = "health-portfolio-monitoring"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.60.0",
]
[tool.poetry]
name = "health-portfolio-monitoring"
version = "0.1.0"
description = ""
authors = ["..."]
package-mode = false